// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ChangeViewController from "./change_view_controller"
application.register("change-view", ChangeViewController)

import ChartController from "./chart_controller"
application.register("chart", ChartController)

import CopyController from "./copy_controller"
application.register("copy", CopyController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import OgpController from "./ogp_controller"
application.register("ogp", OgpController)

import OgpFormController from "./ogp_form_controller"
application.register("ogp-form", OgpFormController)
